export type Database = {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          logo_url: string | null;
          website: string | null;
          phone: string | null;
          address: string | null;
          region: string | null;
          category: string | null;
          companies_house_number: string | null;
          founded_year: number | null;
          employee_count: string | null;
          revenue_bracket: string | null;
          ai_summary: string | null;
          ai_risk_analysis: string | null;
          ai_payment_analysis: string | null;
          ai_review_summary: string | null;
          avg_payment_reliability: number | null;
          avg_communication: number | null;
          avg_site_management: number | null;
          avg_health_and_safety: number | null;
          avg_overall: number | null;
          review_count: number;
          would_work_again_pct: number | null;
          is_verified: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string | null;
          logo_url?: string | null;
          website?: string | null;
          phone?: string | null;
          address?: string | null;
          region?: string | null;
          category?: string | null;
          companies_house_number?: string | null;
          founded_year?: number | null;
          employee_count?: string | null;
          revenue_bracket?: string | null;
          ai_summary?: string | null;
          ai_risk_analysis?: string | null;
          ai_payment_analysis?: string | null;
          ai_review_summary?: string | null;
          avg_payment_reliability?: number | null;
          avg_communication?: number | null;
          avg_site_management?: number | null;
          avg_health_and_safety?: number | null;
          avg_overall?: number | null;
          review_count?: number;
          would_work_again_pct?: number | null;
          is_verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string | null;
          logo_url?: string | null;
          website?: string | null;
          phone?: string | null;
          address?: string | null;
          region?: string | null;
          category?: string | null;
          companies_house_number?: string | null;
          founded_year?: number | null;
          employee_count?: string | null;
          revenue_bracket?: string | null;
          ai_summary?: string | null;
          ai_risk_analysis?: string | null;
          ai_payment_analysis?: string | null;
          ai_review_summary?: string | null;
          avg_payment_reliability?: number | null;
          avg_communication?: number | null;
          avg_site_management?: number | null;
          avg_health_and_safety?: number | null;
          avg_overall?: number | null;
          review_count?: number;
          would_work_again_pct?: number | null;
          is_verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          company_id: string;
          user_id: string;
          project_id: string | null;
          payment_reliability: number;
          communication: number;
          site_management: number;
          health_and_safety: number;
          would_work_again: boolean;
          review_title: string | null;
          review_text: string;
          your_trade: string | null;
          relationship: string | null;
          project_value_bracket: string | null;
          is_verified: boolean;
          is_anonymous: boolean;
          helpful_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          user_id: string;
          project_id?: string | null;
          payment_reliability: number;
          communication: number;
          site_management: number;
          health_and_safety: number;
          would_work_again: boolean;
          review_title?: string | null;
          review_text: string;
          your_trade?: string | null;
          relationship?: string | null;
          project_value_bracket?: string | null;
          is_verified?: boolean;
          is_anonymous?: boolean;
          helpful_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          user_id?: string;
          project_id?: string | null;
          payment_reliability?: number;
          communication?: number;
          site_management?: number;
          health_and_safety?: number;
          would_work_again?: boolean;
          review_title?: string | null;
          review_text?: string;
          your_trade?: string | null;
          relationship?: string | null;
          project_value_bracket?: string | null;
          is_verified?: boolean;
          is_anonymous?: boolean;
          helpful_count?: number;
          created_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          trade: string | null;
          company_name: string | null;
          region: string | null;
          is_verified: boolean;
          review_count: number;
          reputation_score: number;
          created_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          trade?: string | null;
          company_name?: string | null;
          region?: string | null;
          is_verified?: boolean;
          review_count?: number;
          reputation_score?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          trade?: string | null;
          company_name?: string | null;
          region?: string | null;
          is_verified?: boolean;
          review_count?: number;
          reputation_score?: number;
          created_at?: string;
        };
      };
      regions: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          company_count: number;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string | null;
          company_count?: number;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string | null;
          company_count?: number;
        };
      };
      projects: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          company_id: string;
          region: string | null;
          project_type: string | null;
          status: string | null;
          value_bracket: string | null;
          start_date: string | null;
          completion_date: string | null;
          address: string | null;
          lat: number | null;
          lng: number | null;
          ai_summary: string | null;
          review_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string | null;
          company_id: string;
          region?: string | null;
          project_type?: string | null;
          status?: string | null;
          value_bracket?: string | null;
          start_date?: string | null;
          completion_date?: string | null;
          address?: string | null;
          lat?: number | null;
          lng?: number | null;
          ai_summary?: string | null;
          review_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string | null;
          company_id?: string;
          region?: string | null;
          project_type?: string | null;
          status?: string | null;
          value_bracket?: string | null;
          start_date?: string | null;
          completion_date?: string | null;
          address?: string | null;
          lat?: number | null;
          lng?: number | null;
          ai_summary?: string | null;
          review_count?: number;
          created_at?: string;
        };
      };
      blog_posts: {
        Row: {
          id: string;
          slug: string;
          title: string;
          content: string;
          excerpt: string | null;
          category: string | null;
          featured_image_url: string | null;
          is_published: boolean;
          author: string | null;
          seo_title: string | null;
          seo_description: string | null;
          created_at: string;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          content: string;
          excerpt?: string | null;
          category?: string | null;
          featured_image_url?: string | null;
          is_published?: boolean;
          author?: string | null;
          seo_title?: string | null;
          seo_description?: string | null;
          created_at?: string;
          published_at?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          content?: string;
          excerpt?: string | null;
          category?: string | null;
          featured_image_url?: string | null;
          is_published?: boolean;
          author?: string | null;
          seo_title?: string | null;
          seo_description?: string | null;
          created_at?: string;
          published_at?: string | null;
        };
      };
      lead_events: {
        Row: {
          id: string;
          user_id: string | null;
          email: string | null;
          event_type: string;
          source_page: string | null;
          cta_type: string | null;
          synced_to_ghl: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          email?: string | null;
          event_type: string;
          source_page?: string | null;
          cta_type?: string | null;
          synced_to_ghl?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          email?: string | null;
          event_type?: string;
          source_page?: string | null;
          cta_type?: string | null;
          synced_to_ghl?: boolean;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};

// Convenience type aliases
export type Company = Database["public"]["Tables"]["companies"]["Row"];
export type CompanyInsert = Database["public"]["Tables"]["companies"]["Insert"];
export type Review = Database["public"]["Tables"]["reviews"]["Row"];
export type ReviewInsert = Database["public"]["Tables"]["reviews"]["Insert"];
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type Region = Database["public"]["Tables"]["regions"]["Row"];
export type Project = Database["public"]["Tables"]["projects"]["Row"];
export type BlogPost = Database["public"]["Tables"]["blog_posts"]["Row"];
export type LeadEvent = Database["public"]["Tables"]["lead_events"]["Row"];
